apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest  # 使用GitHub Secrets中的用户名
        imagePullPolicy: Always  # 确保每次都拉取最新镜像
        ports:
        - containerPort: 80  # 根据您的应用实际端口调整
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        # 如有需要可以添加环境变量
        # env:
        # - name: ENV_NAME
        #   value: "env_value"
        # - name: SECRET_ENV
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-app-secrets
        #       key: secret-key
        # 如有需要可以添加健康检查
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      # 如有需要可以添加imagePullSecrets
      # imagePullSecrets:
      # - name: regcred
---
# 如果需要Service来暴露应用，可以取消下面的注释
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort  # 可选：ClusterIP, NodePort, LoadBalancer