metadata:
  name: nginx-html
  namespace: default  # 明确指定 default 命名空间
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>ArgoCD DevOps 项目</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                text-align: center; 
                padding: 50px; 
                background-color: #f0f8ff;
            }
            h1 { color: #2c3e50; }
            .container {
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                background: white;
                border-radius: 10px;
                box-shadow: 0 0 10px rgba(0,0,0,0.1);
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>欢迎使用 ArgoCD DevOps 项目</h1>
            <p>容器运行时: <strong>containerd 1.7.13</strong></p>
            <p>操作系统: CentOS Linux 7</p>
            <p>部署时间: $(date)</p>
        </div>
    </body>
    </html>
