apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My App</title>
    </head>
    <body>
      <h1>Hello from Argo CD!</h1>
      <p>Deployed successfully</p>
    </body>
    </html>

