name: Containerd Optimized Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile.nginx
        platforms: linux/amd64  # 仅构建 amd64 镜像（匹配您的节点）
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/argocd-devops-nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Kubernetes tools
      uses: yokawasa/action-setup-kube-tools@v0.9.0
      with:
        kubectl: v1.30.0  # 匹配您的集群版本

    - name: Deploy to Kubernetes
      run: |
        # 替换镜像名称占位符
        sed -i "s|image: nginx:alpine|image: ${{ secrets.DOCKERHUB_USERNAME }}/argocd-devops-nginx:latest|g" apps/nginx/deployment.yaml
        
        # 应用部署配置
        kubectl apply -f apps/nginx/deployment.yaml
        
        # 检查部署状态
        kubectl rollout status deployment/nginx-deployment -n default --timeout=120s
        
        # 获取服务访问信息
        echo "Application deployed!"
        echo "NodePort access: http://<NODE_IP>:30080"
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
