# 定义工作流的名称
name: Docker Build

#定义触发工作流的条件
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          platform: linux/amd64
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 检查deployment是否存在
        id: check-deployment
        uses: actions-hub/kubectl@master
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get deployment my-app --no-headers --ignore-not-found

      - name: 创建deployment(如不存在)
        uses: actions-hub/kubectl@master
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        if: ${{ steps.check-deployment.outputs.stdout == '' }}
        with:
          args: apply -f k8s/my-app-deployment.yaml

      - name: 重启deployment(如存在)
        uses: actions-hub/kubectl@master
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        if: ${{ steps.check-deployment.outputs.stdout != '' }}
        with:
          args: rollout restart deployment my-app